### PR TITLE
Graeme

### PR DESCRIPTION
**Pull request by graemebates**
just added tanner's thing that removes dashes from the phone number, props to geoff for the help on this day

### CODE REVIEW

**Comment by graemebates** [comment]
also dat linting

**Review by geofflorne — APPROVED** [review]
o hel ya

**Comment by tzinck** [comment]
graeme padding his commit stats nice 👍

**Comment by graemebates** [comment]
not padding what do I actually do in that sitch

**Comment by graemebates** [comment]
I squashed and merged so it's all good

**Pull request merged**
