### PR TITLE
Reg verify endpoints

### PR DESCRIPTION
**Pull request by JakeCooper**

### CODE REVIEW

**Comment by JakeCooper** [comment]
kk, couple comments for people:

1) I've added an install script, so run ./install once and it will install a linter for you. Should automatically hook into your IDE, or at least it does with VSCode.
2) Don't use underscores for variable names
3) Always add a statuscode when you return a request. If you don't know which one to do, take inspiration from the ones I've added.
4) I know I said to `failOnError`, but we actually want to `failGracefully` since we don't want the webserver to crash. I'll update the `failGracefully` function later with some logging that isn't trash.

Other than those couple minor things, this looks really good @tzinck. :star2: 

We can merge this as soon as you're happy to do so.

**Comment by JakeCooper** [comment]
:+1:

**Comment by tzinck** [comment]
👍

**Review by tzinck — APPROVED** [review]
👍

**Pull request merged**
